Modify travis file

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -3,36 +3,36 @@ language: php
 matrix:
     include:
         - php: 7.4
-          env: BLACKFIRE=on
+        #   env: BLACKFIRE=on
 
 sudo: false
 
 cache:
     - $HOME/.composer/cache/files
 
-before_install:
-    - |
-        if [[ "$BLACKFIRE" = "on" ]]; then
-            openssl aes-256-cbc -K $encrypted_16ab3ffdcd52_key -iv $encrypted_16ab3ffdcd52_iv -in .blackfire.travis.ini.enc -out ~/.blackfire.ini -d
-            curl -L https://blackfire.io/api/v1/releases/agent/linux/amd64 | tar zxpf -
-            chmod 755 agent && ./agent --config=~/.blackfire.ini --socket=unix:///tmp/blackfire.sock &
-        fi
+# before_install:
+#     - |
+#         if [[ "$BLACKFIRE" = "on" ]]; then
+#             openssl aes-256-cbc -K $encrypted_16ab3ffdcd52_key -iv $encrypted_16ab3ffdcd52_iv -in .blackfire.travis.ini.enc -out ~/.blackfire.ini -d
+#             curl -L https://blackfire.io/api/v1/releases/agent/linux/amd64 | tar zxpf -
+#             chmod 755 agent && ./agent --config=~/.blackfire.ini --socket=unix:///tmp/blackfire.sock &
+#         fi
 
-install:
-    - travis_retry composer install --no-interaction
+# install:
+#     - travis_retry composer install
 
 before_script:
     - composer self-update
     - composer install -n
-    - php bin/console doctrine:schema:update --force
-    - php bin/console doctrine:fixtures:load -n
-    - phpenv config-rm xdebug.ini || true
-    - |
-        if [[ "$BLACKFIRE" = "on" ]]; then
-            curl -L https://blackfire.io/api/v2/releases/probe/php/linux/amd64/$(php -r "echo PHP_MAJOR_VERSION . PHP_MINOR_VERSION;")-zts | tar zxpf -
-            echo "extension=$(pwd)/$(ls blackfire-*.so | tr -d '[[:space:]]')" > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/blackfire.ini
-            echo "blackfire.agent_socket=unix:///tmp/blackfire.sock" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/blackfire.ini
-        fi
+    # - php bin/console doctrine:schema:update --force
+    # - php bin/console doctrine:fixtures:load -n
+    # - phpenv config-rm xdebug.ini || true
+    # - |
+    #     if [[ "$BLACKFIRE" = "on" ]]; then
+    #         curl -L https://blackfire.io/api/v2/releases/probe/php/linux/amd64/$(php -r "echo PHP_MAJOR_VERSION . PHP_MINOR_VERSION;")-zts | tar zxpf -
+    #         echo "extension=$(pwd)/$(ls blackfire-*.so | tr -d '[[:space:]]')" > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/blackfire.ini
+    #         echo "blackfire.agent_socket=unix:///tmp/blackfire.sock" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/blackfire.ini
+    #     fi
 
 script:
     - php bin/phpunit
